### ISSUE TITLE
Desktop examples should open in dedicated window

### ISSUE THREAD

**Issue by lbwexler** [exhi/toolbox#185]
Desktop examples should open in a dedicated window.  Would be nice to have the launch page be library of buttons (or thumbnails), with text describing the app, and maybe what kinds of features it contains, etc.

**Comment by amcclain** [comment]
Hi - just saw this. Is the idea is to have each example as a dedicated top-level app, with its own App and AppModel?  (I assume that would be required to avoid extra gymnastics that would the code harder to understand.)

Is this more about the code / app structure, not having the additional level of example nesting, or some combo of the two?  I ask as I kind of like having the examples embedded right within Toolbox. It helps to really fill out Toolbox itself nicely, and I don't think the Toolbox tabsets overly distract given that the examples are by design relatively simple apps.  

I could imagine building a more full-feature example app ala PIQ and launching that from Toolbox - the portfolio app could get there with a few more features. I am not entirely sold on breaking out what we have (e.g. the news feed example or Recall app) at this point.

**Comment by lbwexler** [comment]
I am bothered by the toolbox shell, and also think the intro page with buutons would look nice and give us a place to hang useful text about what is in apps.

We can table for now.  Certainly higher priorities...
