### ISSUE TITLE
Examples > Portfolio tab throws from LoadSupport

### ISSUE THREAD

**Issue by febbraiod** [exhi/toolbox#217]
Can easily trigger by using the orders quick filter:

![Screen Shot 2019-07-03 at 2 24 35 PM](https://user-images.githubusercontent.com/15745614/60616588-d2974280-9d9f-11e9-84fd-e9f2fa4deb1f.png)

![Screen Shot 2019-07-03 at 2 24 59 PM](https://user-images.githubusercontent.com/15745614/60616597-d5923300-9d9f-11e9-94e6-5edf5779cfef.png)

**Comment by febbraiod** [comment]
Probably to be fixed in hoist react.

**Comment by lbwexler** [comment]
The run argument should be () => this.loadAsync().  We need to bomb the code in toolbox

My bad for putting this bogus pattern in place in the first place.
Thanks for catching, Don!

**Comment by febbraiod** [comment]
Ha! I told Colin I thought this might be the case, but we thought it might make sense to protect future apps from themselves by fixing in Hoist. Should we not do both?

**Comment by lbwexler** [comment]
I think the "protection" you get from just the null-case here is so minimal
that it gives a false sense of security.

If you really wanted to do this, you could examine the received loadSpec,
and make sure it was actually of the right form and otherwise warn or
throw. But that would be a different change, and not suggesting that we do
that now.

**Comment by lbwexler** [comment]
Fixed this, since I caused it in the first place.  Classic Javascript error

  Thanks Don!
